module.exports = {
	aa: 'aa',
	bb: 'bb',
	cc: 'cc',
	dd: 'dd',
	result: {
		a: undefined,
		b: undefined,
		c: undefined,
		d: undefined,
		a1: 'a1',
		b1: 'b1',
		c1: 'c1',
		d1: 'd1',
		a2: (x) => x.name === 'a2',
		b2: (x) => x.name === 'b2',
		c2: (x) => x.name === 'c2',
		d2: (x) => x.name === 'd2',
		a3: 'a1',
		b3: 'b1',
		c3: 'c1',
		d3: 'd1',
		a4: (x) => x.name === 'a2',
		b4: (x) => x.name === 'b2',
		c4: (x) => x.name === 'c2',
		d4: (x) => x.name === 'd2',
		A5: (x) => x.name === 'A5',
		B5: (x) => x.name === 'B5',
		C5: (x) => x.name === 'C5',
		D5: (x) => x.name === 'D5',
	},
}
