module.exports = {
	aa: 'aa',
	bb: 'bb',
	cc: 'cc',
	dd: 'dd',
	result: {
		a: 'a0',
		b: 'b0',
		c: 'c0',
		d: 'd0',
		a1: undefined,
		b1: undefined,
		c1: undefined,
		d1: undefined,
		a2: undefined,
		b2: undefined,
		c2: undefined,
		d2: undefined,
		a3: undefined,
		b3: undefined,
		c3: undefined,
		d3: undefined,
		a4: undefined,
		b4: undefined,
		c4: undefined,
		d4: undefined,
		A5: undefined,
		B5: undefined,
		C5: undefined,
		D5: undefined,
	},
};
